services:
  ajax2mqtt:
    container_name: ajax2mqtt
    image: ghcr.io/ingria/ajax2mqtt:latest
    privileged: false
    user: "65534:65534" # nobody:nobody, change me!
    group_add:
      - dialout
    devices:
      - /dev/your-local-usb-tty-adapter:/dev/ttyUSB0
    restart: unless-stopped
    network_mode: host
    environment:
      - A2M_SERIAL_PORT=/dev/ttyUSB0
      - A2M_HASS_ENABLED=true
      - A2M_HASS_BASE_TOPIC=homeassistant
      - A2M_LOG_LEVEL=error
      - A2M_MQTT_ADDRESS=mqtt://127.0.0.1
      - A2M_MQTT_PASSWORD=
      - A2M_MQTT_USERNAME=
      - A2M_MQTT_BASE_TOPIC=ajax2mqtt
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: 1
    depends_on:
      - homeassistant
