export const schema = Object.freeze({
    tamper: {
        '@type': 'binary_sensor',
        'device_class': 'tamper',
        'payload_off': false,
        'payload_on': true,
    },
    noise: {
        '@type': 'sensor',
        'unit_of_measurement': 'dB',
        'icon': 'mdi:access-point-remove',
        'entity_category': 'diagnostic',
        'state_class': 'measurement',
        'enabled_by_default': false,
    },
    rssi: {
        '@type': 'sensor',
        'device_class': 'signal_strength',
        'unit_of_measurement': 'dBm',
        'entity_category': 'diagnostic',
        'state_class': 'measurement',
        'enabled_by_default': false,
        'name': 'RSSI',
    },
    temperature: {
        '@type': 'sensor',
        'device_class': 'temperature',
        'unit_of_measurement': '°C',
        'entity_category': 'diagnostic',
        'state_class': 'measurement',
        'enabled_by_default': false,
    },
    voltage: {
        '@type': 'sensor',
        'device_class': 'voltage',
        'unit_of_measurement': 'V',
        'entity_category': 'diagnostic',
        'state_class': 'measurement',
        'enabled_by_default': false,
    },
    battery: {
        '@type': 'sensor',
        'device_class': 'battery',
        'unit_of_measurement': '%',
        'entity_category': 'diagnostic',
        'name': 'Battery voltage',
    },
    battery_low: {
        '@type': 'binary_sensor',
        'device_class': 'battery',
        'entity_category': 'diagnostic',
        'payload_off': false,
        'payload_on': true,
        'name': 'Battery status',
    },
    backup_battery_voltage: {
        '@type': 'sensor',
        'device_class': 'voltage',
        'unit_of_measurement': 'V',
        'entity_category': 'diagnostic',
        'state_class': 'measurement',
        'name': 'Backup battery voltage',
        'enabled_by_default': false,
    },
    backup_battery_low: {
        '@type': 'binary_sensor',
        'device_class': 'battery',
        'entity_category': 'diagnostic',
        'payload_off': false,
        'payload_on': true,
        'name': 'Backup battery status',
    },
    smoke: {
        '@type': 'binary_sensor',
        'enabled_by_default': true,
        'device_class': 'smoke',
        'payload_off': false,
        'payload_on': true,
    },
    smoke_chamber_malfunction: {
        '@type': 'binary_sensor',
        'enabled_by_default': true,
        'device_class': 'problem',
        'payload_off': false,
        'payload_on': true,
        'name': 'Smoke chamber malfunction',
    },
    chamber_dust_percent: {
        '@type': 'sensor',
        'enabled_by_default': true,
        'unit_of_measurement': '%',
        'entity_category': 'diagnostic',
        'icon': 'mdi:blur-radial',
        'name': 'Smoke chamber dust percent',
    },
    co: {
        '@type': 'binary_sensor',
        'enabled_by_default': true,
        'device_class': 'carbon_monoxide',
        'payload_off': false,
        'payload_on': true,
    },
    co_chamber_malfunction: {
        '@type': 'binary_sensor',
        'enabled_by_default': true,
        'device_class': 'problem',
        'payload_off': false,
        'payload_on': true,
        'name': 'CO chamber malfunction',
    },
});
