name: Docker Image CI
on:
  push:
    branches:
      - master
    paths:
      - src/*
      - .github/workflows/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Generate version tag
      id: version
      shell: bash
      run: |
        output=value=$(cat package.json | tr -d '\n' | tr -d ' ' | cut -d'"' -f4)
        echo $output
        for l in $output; do
          echo $l >> $GITHUB_OUTPUT
        done

    - name: Docker meta
      id: metadata
      uses: docker/metadata-action@v5
      with:
        flavor: |
          latest=true
        images: |
          name=ghcr.io/${{ github.repository_owner }}/ajax2mqtt            
        tags: |
          type=raw,value=${{ steps.version.outputs.value }}      

    - name: Build and push image
      uses: docker/build-push-action@v6.5.0
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v6
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
